[package]
name = "Fastdop"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11.7"
tokio = { version = "1.44.1", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4"] }
ble-peripheral-rust = "0.2.0"
